# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, TensorDataset
from torchvision.models import alexnet
from sklearn.decomposition import PCA
import numpy as np
import torch.optim as optim

base_transform = transforms.Compose([
    transforms.ToTensor(),
])

# remember to create the corresponding directory
os.makedirs('./results/data', exist_ok=True)
train_dataset = datasets.MNIST(root='./results/data', train=True, transform=base_transform, download=True)
test_dataset = datasets.MNIST(root='./results/data', train=False, transform=base_transform, download=True)

def apply_pca(dataset, pca_model=None, n_components=8):
    images = torch.stack([img for img, _ in dataset])  # [N, 1, 28, 28]
    labels = torch.tensor([label for _, label in dataset])
    flat_images = images.view(images.size(0), -1).numpy()

    if pca_model is None:
        pca_model = PCA(n_components=n_components)
        transformed = pca_model.fit_transform(flat_images)
    else:
        transformed = pca_model.transform(flat_images)

    return torch.tensor(transformed, dtype=torch.float32), labels, pca_model

X_train, y_train, pca_model = apply_pca(train_dataset)
X_test, y_test, _ = apply_pca(test_dataset, pca_model)

train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=64, shuffle=True)
test_loader = DataLoader(TensorDataset(X_test, y_test), batch_size=64, shuffle=False)

image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.Grayscale(num_output_channels=3),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

teacher_dataset = torchvision.datasets.MNIST(root='./results/data', train=True, download=True, transform=image_transform)
teacher_loader = DataLoader(teacher_dataset, batch_size=64, shuffle=False)

teacher = alexnet(pretrained=True)
teacher.classifier[6] = nn.Linear(4096, 10)
for param in teacher.parameters():
    param.requires_grad = False
teacher.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

# Prepare test set for teacher
teacher_test_dataset = torchvision.datasets.MNIST(
    root='./results/data',
    train=False,
    download=True,
    transform=image_transform  # same as for teacher
)
teacher_test_loader = DataLoader(teacher_test_dataset, batch_size=64, shuffle=False)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Evaluate teacher
def evaluate_teacher(model, dataloader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return 100 * correct / total

teacher.to(device)
teacher_accuracy = evaluate_teacher(teacher, teacher_test_loader)
print(f"Teacher Test Accuracy: {teacher_accuracy:.2f} [%]")

# 2. Fine-tune AlexNet on MNIST
train_ds = torchvision.datasets.MNIST(root='./results/data', train=True, download=True, transform=image_transform)
test_ds  = torchvision.datasets.MNIST(root='./results/data', train=False, download=True, transform=image_transform)
train_loader = DataLoader(train_ds, batch_size=64, shuffle=True)
test_loader  = DataLoader(test_ds, batch_size=64, shuffle=False)

teacher = alexnet(pretrained=True)
teacher.classifier[6] = nn.Linear(4096, 10)
teacher.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(teacher.parameters(), lr=1e-4)

print("Fine-tuning AlexNet on MNIST...")
teacher.train()

for epoch in range(5):
    total_loss = 0.0
    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = teacher(imgs)
        loss = criterion(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    test_acc = evaluate_teacher(teacher, test_loader)
    print(f"Epoch {epoch+1}: Loss: {total_loss / len(train_loader):.4f}| Test Accuracy: {test_acc:.2f} [%]")

# Evaluate fine-tuned teacher
def evaluate(model, dataloader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for imgs, labels in dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            _, predicted = outputs.max(1)
            correct += (predicted == labels).sum().item()
            total += labels.size(0)
    return 100 * correct / total

teacher_acc = evaluate(teacher, test_loader)
print(f"---> Fine-Tuned AlexNet Test Accuracy: {teacher_acc:.2f} [%]")

logit_save_path = "MNIST/teachers/mnist_train_logits_alexnet.npy"
all_logits = []
with torch.no_grad():
    for imgs, _ in DataLoader(train_ds, batch_size=1000, shuffle=False):
        imgs = imgs.to(device)
        logits = teacher(imgs)
        all_logits.append(logits.cpu())

logits_tensor = torch.cat(all_logits)
np.save(logit_save_path, logits_tensor.numpy())
print(f"[Done] Logits saved at {logit_save_path}")

# Freeze teacher
for param in teacher.parameters():
    param.requires_grad = False
teacher.eval()

# apply PCA to student inputs
base_transform = transforms.ToTensor()
raw_train_ds = torchvision.datasets.MNIST(root='./results/data', train=True, download=True, transform=base_transform)
raw_test_ds  = torchvision.datasets.MNIST(root='./results/data', train=False, download=True, transform=base_transform)

X_train, y_train, pca_model = apply_pca(raw_train_ds)
X_test, y_test, _ = apply_pca(raw_test_ds, pca_model)

student_train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=64, shuffle=True)
student_test_loader  = DataLoader(TensorDataset(X_test, y_test), batch_size=64, shuffle=False)

# Precompute teacher outputs for distillation
teacher_full_loader = DataLoader(train_ds, batch_size=64, shuffle=False)
teacher_logits_all = []
with torch.no_grad():
    for imgs, _ in teacher_full_loader:
        imgs = imgs.to(device)
        logits = teacher(imgs).cpu()
        teacher_logits_all.append(logits)
teacher_logits_all = torch.cat(teacher_logits_all).to(device)

print("Shape:", teacher_logits_all.shape)

# Define new student model for 8D input
class StudentMLP(nn.Module):
    def __init__(self):
        super(StudentMLP, self).__init__()
        self.fc1 = nn.Linear(8, 10)
        self.fc2 = nn.Linear(10, 10)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        return self.fc2(x)

student = StudentMLP().to(device)
optimizer = optim.Adam(student.parameters(), lr=0.001)

def distillation_loss(student_logits, teacher_logits, labels, T=2.0, alpha=0.7):
    loss_ce = criterion(student_logits, labels)
    loss_kl = F.kl_div(
        F.log_softmax(student_logits / T, dim=1),
        F.softmax(teacher_logits / T, dim=1),
        reduction='batchmean'
    ) * (T * T)
    return alpha * loss_ce + (1 - alpha) * loss_kl

torch.manual_seed(21)
student = StudentMLP().to(device)
optimizer = optim.Adam(student.parameters(), lr=0.001)

# Train A digital Student with Distillation
print("Training Digital Student via Distillation...")
for epoch in range(20):
    student.train()
    total_loss = 0.0
    for i, (x, labels) in enumerate(student_train_loader):
        x, labels = x.to(device), labels.to(device)
        s_logits = student(x)
        t_logits = teacher_logits_all[i*64:i*64 + x.size(0)]
        loss = distillation_loss(s_logits, t_logits, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss = {total_loss / len(student_train_loader):.4f}")

student_acc = evaluate(student, student_test_loader)
print(f"Distilled Digital Student Test Accuracy: {student_acc:.2f} [%]")

# Compare with training student from scratch (no distillation)
torch.manual_seed(21)
student_scratch = StudentMLP().to(device)
optimizer_scratch = optim.Adam(student_scratch.parameters(), lr=0.001)

print("Training Student from Scratch (No Distillation)...")
for epoch in range(20):
    student_scratch.train()
    total_loss = 0.0
    for x, labels in student_train_loader:
        x, labels = x.to(device), labels.to(device)
        outputs = student_scratch(x)
        loss = criterion(outputs, labels)
        optimizer_scratch.zero_grad()
        loss.backward()
        optimizer_scratch.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss = {total_loss / len(student_train_loader):.4f}")

# 9. Evaluate student trained from scratch
scratch_acc = evaluate(student_scratch, student_test_loader)
print(f"--> Student from Scratch Test Accuracy: {scratch_acc:.2f} [%]")

"""## LeNet"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import os
from copy import deepcopy

# Define LeNet architecture
class LeNet(nn.Module):
    def __init__(self, num_classes=10):
        super(LeNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 6, kernel_size=5),   # 28x28 -> 24x24
            nn.Tanh(),
            nn.AvgPool2d(2),                  # 24x24 -> 12x12
            nn.Conv2d(6, 16, kernel_size=5),  # 12x12 -> 8x8
            nn.Tanh(),
            nn.AvgPool2d(2),                  # 8x8 -> 4x4
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(16 * 4 * 4, 120),
            nn.Tanh(),
            nn.Linear(120, 84),
            nn.Tanh(),
            nn.Linear(84, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# Fine-tune LeNet on MNIST
def fine_tune_lenet_on_mnist(epochs=5, batch_size=64, lr=0.001, save_path="MNIST/teachers/lenet_mnist.pth"):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # MNIST data
    transform = transforms.Compose([
        transforms.Resize((28, 28)),
        transforms.ToTensor()
    ])
    train_data = datasets.MNIST(root="./data", train=True, transform=transform, download=True)
    test_data = datasets.MNIST(root="./data", train=False, transform=transform, download=True)
    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=False)

    # Model, Loss, Optimizer
    model = LeNet().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.9)  # Halve LR every 3 epochs

    best_acc, best_model = 0, None

    # Training loop
    for epoch in range(epochs):
        model.train()
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        scheduler.step()  # Adjust learning rate

        # Evaluation on test set
        model.eval()

        correct, total = 0, 0
        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        acc = 100.0 * correct / total
        print(f"Epoch {epoch+1}/{epochs}, Test Accuracy: {acc:.2f}%")

        if acc > best_acc:
            # Save the fine-tuned model
            torch.save(model.state_dict(), save_path)
            print(f"Model saved to: {save_path}")
            best_acc = acc
            best_model = deepcopy(model)

    logit_save_path = "MNIST/teachers/mnist_train_logits_lenet.npy"
    all_logits = []
    with torch.no_grad():
        for imgs, _ in DataLoader(train_data, batch_size=1000, shuffle=False):
            imgs = imgs.to(device)
            logits = best_model(imgs)
            all_logits.append(logits.cpu())

    logits_tensor = torch.cat(all_logits)
    np.save(logit_save_path, logits_tensor.numpy())
    print(f"[Done] Logits saved at {logit_save_path}")

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import os
from copy import deepcopy

# Define LeNet architecture
class LeNet(nn.Module):
    def __init__(self, num_classes=10):
        super(LeNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 6, kernel_size=5),   # 28x28 → 24x24
            nn.Tanh(),
            nn.AvgPool2d(2),                  # 24x24 → 12x12
            nn.Conv2d(6, 16, kernel_size=5),  # 12x12 → 8x8
            nn.Tanh(),
            nn.AvgPool2d(2),                  # 8x8 → 4x4
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(16 * 4 * 4, 120),
            nn.Tanh(),
            nn.Linear(120, 84),
            nn.Tanh(),
            nn.Linear(84, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x


# Fine-tune LeNet on MNIST
def fine_tune_lenet_on_mnist(epochs=5, batch_size=64, lr=0.001, save_path="MNIST/teachers/lenet_mnist.pth"):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # MNIST data
    transform = transforms.Compose([
        transforms.Resize((28, 28)),
        transforms.ToTensor()
    ])
    train_data = datasets.MNIST(root="./results/data", train=True, transform=transform, download=True)
    test_data = datasets.MNIST(root="./results/data", train=False, transform=transform, download=True)
    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=False)

    # Model, Loss, Optimizer
    model = LeNet().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.9)  # Halve LR every 3 epochs

    best_acc, best_model = 0, None

    # Training loop
    for epoch in range(epochs):
        model.train()
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        scheduler.step()  # Adjust learning rate

        # Evaluation on test set
        model.eval()

        correct, total = 0, 0
        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        acc = 100.0 * correct / total
        print(f"Epoch {epoch+1}/{epochs}, Test Accuracy: {acc:.2f}%")

        if acc > best_acc:
            # Save the fine-tuned model
            torch.save(model.state_dict(), save_path)
            print(f"Model saved to: {save_path}")
            best_acc = acc
            best_model = deepcopy(model)

    logit_save_path = "MNIST/teachers/mnist_train_logits_lenet.npy"
    all_logits = []
    with torch.no_grad():
        for imgs, _ in DataLoader(train_data, batch_size=1000, shuffle=False):
            imgs = imgs.to(device)
            logits = best_model(imgs)
            all_logits.append(logits.cpu())

    logits_tensor = torch.cat(all_logits)
    np.save(logit_save_path, logits_tensor.numpy())
    print(f"[Done] Logits saved at {logit_save_path}")

fine_tune_lenet_on_mnist(epochs = 20, batch_size=128)

fine_tune_lenet_on_mnist(epochs = 20, batch_size=32, lr=0.001)